Models/Bon.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace WebApplication2.Models
{
    public class Bon
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [Range(1, int.MaxValue, ErrorMessage = "Kwota musi byc wieksza od 0")]
        [Display(Name ="Wartość bonu")]
        public int Value { get; set; }

        [Display(Name ="Produkt")]
        public int  ProductID { get; set; }

        [ForeignKey("ProductID")]
        [Display(Name ="Produkt")]
        public virtual Product product { get; set; }
        public bool Used { get; set; }
    }
}

Controllers/BonController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data;
using WebApplication2.Models;
using WebApplication2.Models.ViewModel;

namespace WebApplication2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class BonController : Controller
    {
        private readonly ApplicationDbContext _db;

        public BonController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            IEnumerable<Bon> objlist = _db.Bony;
            foreach (var obj in objlist)
            {
                obj.product = _db.Products.FirstOrDefault(u => u.Id == obj.ProductID);
            }
            return View(objlist);
        }
        public IActionResult Create()
        {

            BonVM expenseVM = new BonVM()
            {
                bon = new Bon(),
                TypeDropDown = _db.Products.Select(i => new SelectListItem
                {
                    Text = i.ProductName,
                    Value = i.Id.ToString()
                })
            };

            return View(expenseVM);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BonVM obj)
        {
            obj.bon.Used = false;
            if (ModelState.IsValid)
            {
                _db.Bony.Add(obj.bon);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Bony.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            obj.product = _db.Products.FirstOrDefault(u => u.Id == obj.ProductID);
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(Bon obj)
        {
            if (obj == null)
            {
                return NotFound();
            }
            _db.Bony.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Update(int? id)
        {
            if (id == null || id == 0)
            {
                return NotFound();
            }
            var obj = _db.Bony.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            IEnumerable<SelectListItem> TypeDropDown = _db.Products.Select(i => new SelectListItem
            {
                Text = i.ProductName,
                Value = i.Id.ToString()
            });

            ViewBag.TypeDropDown = TypeDropDown;
            return View(obj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(Bon obj)
        {
            if (ModelState.IsValid)
            {
                _db.Bony.Update(obj);
                _db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(obj);
        }
    }
}

Views/Bon/Create.cshtml
@model WebApplication2.Models.ViewModel.BonVM

<form method="post" asp-action="Create">
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger">

        </div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Dodaj bon</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="bon.Value"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="bon.product"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="bon.Value" class="form-control" />
                        <span asp-validation-for="bon.Value" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <select asp-for="bon.ProductID" asp-items="@Model.TypeDropDown" class="form-control">
                            <option selected>--Select Expense type --</option>
                        </select>
                        <span asp-validation-for="bon.ProductID" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col-6 text-center">
                            <input type="submit" class="btn btn-primary" value="Dodaj" />
                        </div>
                        <div class="col-6 text-center">
                            <a asp-action="Index" class="btn btn-success">Powrót</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

Views/Bon/Delete.cshtml
@model WebApplication2.Models.Bon

<form method="post" asp-action="Delete">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Usuń bon</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="ProductID"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Value"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="product.ProductName" disabled class="form-control" />
                    </div>
                    <div class="col-6">
                        <input asp-for="Value" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Usuń" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Cofnij</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Bon/Index.cshtml
@model IEnumerable<WebApplication2.Models.Bon>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista bonów
            </h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Bon" asp-action="Create" class="btn btn-primary">Utwórz nowy bon</a>
        </div>
        <br />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Id</th>
                    <th scope="col">Nazwa Produktu</th>
                    <th scope="col">Kwota Rabatu</th>
                    <th scope="col">Opcje</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>@item.Id</td>
                        <td>@item.product.ProductPrice</td>
                        <td>@item.Value</td>
                        <td class="tab">
                            <div class="col-6">
                                <a asp-controller="Bon" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary me-1 text-start" role="button">Zaktualizuj</a>
                                <a asp-controller="Bon" asp-action="Delete" asp-route-Id="@item.Id" asp-for="Id" class="btn btn-danger" role="button">Usuń</a>
                            </div>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
        <div class="col-6 text-right">
            <a asp-controller="Home" asp-action="Admin" class="btn btn-primary">Powrót</a>
        </div>






    </div>
</div>

Views/Bon/Update.cshtml
@model WebApplication2.Models.Bon

<form method="post" asp-action="Update">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        <div asp-validation-summary="All" class="text-danger">

        </div>
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Edytuj bon</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Value"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="product"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Value" class="form-control" />
                        <span asp-validation-for="Value" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <select asp-for="ProductID" asp-items="@ViewBag.TypeDropDown" class="form-control">
                            <option selected>--Select Expense type --</option>
                        </select>
                        <span asp-validation-for="ProductID" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-info w-75" value="Edytuj" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-danger w-75">Cofnij</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>