Controllers/CashiersController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Identity.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Owin.Security.DataProtection;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebApplication2.Data;
using WebApplication2.Models;
using WebApplication2.Models.ViewModel;

namespace WebApplication2.Controllers
{
    [Authorize(Roles = "Admin")]
    public class CashiersController : Controller
    {
        private readonly ApplicationDbContext _db;
        UserManager<ApplicationUser> _userManager;
        SignInManager<ApplicationUser> _signInManager;
        RoleManager<IdentityRole> _roleManager;

        public CashiersController(ApplicationDbContext db, UserManager<ApplicationUser> userManager,
        SignInManager<ApplicationUser> signInManager,
        RoleManager<IdentityRole> roleManager)
        {
            _db = db;
            _userManager = userManager;
            _signInManager = signInManager;
            _roleManager = roleManager;
        }
        public IActionResult Index()
        {
            var doctors = (from user in _db.Users
                           join userRoles in _db.UserRoles on user.Id equals userRoles.UserId
                           join roles in _db.Roles.Where(x => x.Name == Role.Role.Kasjer) on userRoles.RoleId equals roles.Id
                           select new CashierVM
                           {
                               Id = user.Id,
                               Name = user.Name,
                               Surname = user.Surname,
                               Email = user.Email,
                               Transactions = user.Transactions
                           }
                 ).ToList();
            return View(doctors);
        }

        public async Task<ActionResult> Delete(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> DeletePost(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }

            await _userManager.DeleteAsync(user);

            _db.SaveChanges();

            return RedirectToAction("Index");
        }

        public async Task<ActionResult> Update(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            return View(user);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST Update
        public async Task<ActionResult> UpdatePost(ApplicationUser obj)
        {
            string id = obj.Id;
            var user = await _userManager.FindByIdAsync(id);
            user.Name = obj.Name;
            user.Surname = obj.Surname;
            user.Email = obj.Email;
            user.UserName = obj.Email;
            if (user == null)
            {
                return NotFound();
            }
            await _userManager.UpdateAsync(user);
            _db.SaveChanges();
            return RedirectToAction("Index");

        }

        public async Task<ActionResult> ChangePassword(string? id)
        {
            var user = await _userManager.FindByIdAsync(id);
            var changepasswordvm = new ChangePasswordVM
            {
                Id = user.Id,
                Password = null
            };
            if (user == null)
            {
                return NotFound();
            }
            return View(changepasswordvm);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        //POST Update
        public async Task<ActionResult> ChangePassword(ChangePasswordVM obj)
        { 
            if(ModelState.IsValid)
            {
                ViewBag.Message = "Hasło zmienione pomyślnie!";
                var user = await _userManager.FindByIdAsync(obj.Id);
                await _userManager.RemovePasswordAsync(user);
                var result = await _userManager.AddPasswordAsync(user, obj.Password);
                foreach (var error in result.Errors)
                {
                    ModelState.AddModelError("", error.Description);
                    ViewBag.Message = "";
                }
            }
            return View(obj);


        }
    }
}

Views/Cashiers/ChangePassword.cshtml
@model WebApplication2.Models.ViewModel.ChangePasswordVM


@{
    ViewData["Title"] = "Change Password";
}


<form method="post" asp-action="ChangePassword">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-5">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <p> @ViewBag.Message </p>
        <div class="from-group row">
            <h2 class="text-black-50 text-center pl-3">Zmodyfikuj dane o kasjerze</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="Password"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Id" disabled class="form-control" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="col-6">
                        <input asp-for="Password" class="form-control" />
                        <span asp-validation-for="Password" class="text-danger"></span>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6 text-center">
                        <input type="submit" class="btn btn-primary" value="Zaktualizuj" />
                    </div>
                    <div class="col-6">
                        <a asp-action="Index" class="btn btn-success w-75">Cofnij</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

@section Scripts{
    <partial name="_ValidationScriptsPartial" />
}

Views/Cashiers/Delete.cshtml
@model WebApplication2.Models.ApplicationUser

<form method="post" asp-action="DeletePost">
    <input asp-for="Id" hidden />
    <div class="border p-3">
        @*<div asp-validation-summary="ModelOnly" class="text-danger"></div>*@
        <div class="form-group row">
            <h2 class="text-black-50 pl-3">Usuń kasjera</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-6">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-6">
                        <label asp-for="Surname"></label>
                    </div>

                </div>
                <div class="form-group row">
                    <div class="col-6">
                        <input asp-for="Name" disabled class="form-control" />
                    </div>
                    <div class="col-6">
                        <input asp-for="Surname" disabled class="form-control" />
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-8 offset-2 row">
                        <div class="col">
                            <input type="submit" class="btn btn-danger w-75" value="Usuń" />
                        </div>
                        <div class="col">
                            <a asp-action="Index" class="btn btn-success w-75">Cofnij</a>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</form>

@section Scripts{
    @{
        <partial name="_ValidationScriptsPartial" />
    }
}

Views/Cashiers/Index.cshtml
@model IEnumerable<WebApplication2.Models.ViewModel.CashierVM>

<div class="container p-3">
    <div class="row pt-4">
        <div class="col-6">
            <h2 class="text-primary">
                Lista kasjerów
            </h2>
        </div>
        <div class="col-6 text-right">
            <a asp-controller="Account" asp-action="Register" class="btn btn-primary">Dodaj kasjera lub admina</a>
        </div>
        <br />
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">Imię</th>
                    <th scope="col">Nazwisko</th>
                    <th scope="col">E-mail</th>
                    <th scope="col">Opcje</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                <tr>
                    <td>@item.Name</td>
                    <td>@item.Surname</td>
                    <td>@item.Email</td>

                    <td class="tab">
                        <div class="">
                            <a asp-controller="Cashiers" asp-action="Update" asp-route-Id="@item.Id" class="btn btn-primary me-1 text-start col-3" role="button">Zmień</a>
                            <a asp-controller="Cashiers" asp-action="Delete" asp-route-Id="@item.Id" asp-for="Id" class="btn btn-danger col-3" role="button">Usuń</a>
                            <a asp-controller="Cashiers" asp-action="ChangePassword" asp-route-Id="@item.Id" asp-for="Id" class="btn btn-danger col-3" role="button">Zmień hasło</a>
                        </div>
                    </td>
                </tr>
                }
            </tbody>
        </table>
        <div class="col-6 text-right">
            <a asp-controller="Home" asp-action="Admin" class="btn btn-primary">Powrót</a>
        </div>





    </div>
</div>

Views/Cashiers/Update.cshtml
@model WebApplication2.Models.ApplicationUser


@{
    ViewData["Title"] = "Update";
}


<form method="post" asp-action="UpdatePost">
    <input asp-for="Id" hidden />
    <div class="border p-3 mt-5">
        <div asp-validation-summary="ModelOnly" class="text-danger"></div>
        <div class="from-group row">
            <h2 class="text-black-50 text-center pl-3">Zmodyfikuj dane o kasjerze</h2>
        </div>
        <div class="row">
            <div class="col-12">
                <div class="form-group row">
                    <div class="col-3">
                        <label asp-for="Id"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="Name"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="Surname"></label>
                    </div>
                    <div class="col-3">
                        <label asp-for="Email"></label>
                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-3">
                        <input asp-for="Id" disabled class="form-control" />
                        <span asp-validation-for="Id" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="Name" class="form-control" />
                        <span asp-validation-for="Name" class="text-danger"></span>
                    </div>
                    <div class="col-3">
                        <input asp-for="Surname" class="form-control" />
                        <span asp-validation-for="Surname" class="text-danger"></span>

                    </div>
                    <div class="col-3">
                        <input asp-for="Email" class="form-control" />
                        <span asp-validation-for="Email" class="text-danger"></span>

                    </div>
                </div>
                <div class="form-group row">
                    <div class="col-6 text-center">
                        <input type="submit" class="btn btn-primary" value="Zaktualizuj" />
                    </div>
                    <div class="col">
                        <a asp-action="Index" class="btn btn-success w-75">Cofnij</a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>